# Generated by Django 3.2 on 2021-04-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('description', models.CharField(max_length=10)),
                ('pressure', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('air_quality', models.IntegerField()),
            ],
        ),
    ]
