# Generated by Django 3.2 on 2021-04-26 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 12, 31, 26, 663890)),
        ),
    ]
