# Generated by Django 3.2 on 2021-04-27 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210426_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 18, 19, 12, 509469)),
        ),
    ]
